/**
 * Patch products.ts with Printify created_at (no image re-download).
 * Usage: npx tsx scripts/patch-created-at.ts
 */
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { etsyUrls } from "../src/data/etsy-urls";
import { products } from "../src/data/products";
import type { Product } from "../src/data/product-types";

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const OUT = path.join(ROOT, "src", "data", "products.ts");

function loadEnvFile(filePath: string) {
  if (!fs.existsSync(filePath)) return;
  for (const line of fs.readFileSync(filePath, "utf8").split(/\r?\n/)) {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith("#")) continue;
    const eq = trimmed.indexOf("=");
    if (eq === -1) continue;
    const key = trimmed.slice(0, eq).trim();
    let value = trimmed.slice(eq + 1).trim();
    if (
      (value.startsWith('"') && value.endsWith('"')) ||
      (value.startsWith("'") && value.endsWith("'"))
    ) {
      value = value.slice(1, -1);
    }
    if (process.env[key] == null) process.env[key] = value;
  }
}

function escapeTsString(value: string): string {
  return value.replace(/\\/g, "\\\\").replace(/"/g, '\\"');
}

async function main() {
  loadEnvFile(path.join(ROOT, ".env.local"));
  const token = process.env.PRINTIFY_API_TOKEN?.trim();
  const shopId = process.env.PRINTIFY_SHOP_ID?.trim();
  if (!token || !shopId) throw new Error("missing env");

  const byId = new Map<string, string>();
  let page = 1;
  let last = 1;
  do {
    const res = await fetch(
      `https://api.printify.com/v1/shops/${shopId}/products.json?limit=50&page=${page}`,
      { headers: { Authorization: `Bearer ${token}` } },
    );
    if (!res.ok) throw new Error(`Printify ${res.status}`);
    const json = (await res.json()) as {
      last_page?: number;
      data: Array<{ id: string; created_at?: string }>;
    };
    for (const p of json.data) {
      if (p.created_at) byId.set(p.id, p.created_at);
    }
    last = json.last_page ?? page;
    page += 1;
  } while (page <= last);

  let patched = 0;
  const next: Product[] = products.map((p) => {
    const createdAt = p.printifyId ? byId.get(p.printifyId) : undefined;
    if (createdAt && createdAt !== p.createdAt) patched += 1;
    return createdAt ? { ...p, createdAt } : p;
  });

  const fileBody = `/**
 * AUTO-GENERATED by \`npm run sync:printify\` — do not edit by hand.
 * Re-run the sync after changing products in Printify.
 * Per-listing Etsy URLs live in etsy-urls.ts (applied at runtime too).
 */
import type { Product } from "./product-types";
import { ETSY_SHOP_URL } from "./product-types";
import { etsyUrls } from "./etsy-urls";

export type { Product } from "./product-types";
export { ETSY_SHOP_URL } from "./product-types";

export const products: Product[] = [
${next
  .map((p) => {
    const backLine = p.imageBackSrc
      ? `\n    imageBackSrc: "${escapeTsString(p.imageBackSrc)}",`
      : "";
    const listing = etsyUrls[p.slug];
    const etsyExpr = listing
      ? `etsyUrls["${escapeTsString(p.slug)}"]`
      : "ETSY_SHOP_URL";
    const colors = p.colors ?? [];
    const colorsBlock = colors
      .map((c) => {
        const cBack = c.backSrc
          ? `,\n        backSrc: "${escapeTsString(c.backSrc)}"`
          : "";
        return `      {
        name: "${escapeTsString(c.name)}",
        frontSrc: "${escapeTsString(c.frontSrc)}"${cBack}
      }`;
      })
      .join(",\n");
    const tagsBlock =
      p.tags && p.tags.length > 0
        ? `\n    tags: [${p.tags.map((t) => `"${escapeTsString(t)}"`).join(", ")}],`
        : "";
    const createdBlock = p.createdAt
      ? `\n    createdAt: "${escapeTsString(p.createdAt)}",`
      : "";
    return `  {
    slug: "${escapeTsString(p.slug)}",
    printifyId: "${escapeTsString(p.printifyId ?? "")}",
    name: "${escapeTsString(p.name)}",
    description: "${escapeTsString(p.description)}",
    priceCents: ${p.priceCents},
    imageSrc: "${escapeTsString(p.imageSrc)}",${backLine}
    imageAlt: "${escapeTsString(p.imageAlt)}",
    colors: [
${colorsBlock}
    ],${tagsBlock}${createdBlock}
    etsyUrl: ${etsyExpr},
    isPlaceholder: false,
  }`;
  })
  .join(",\n")}
];
`;

  fs.writeFileSync(OUT, fileBody, "utf8");
  console.log(`Patched createdAt on ${patched} product(s); wrote ${next.length}.`);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
